### ISSUE TITLE
Question: How to launch under cursor?

### ISSUE THREAD

**Issue by tecosaur** [zachcurry/emacs-anywhere#63]
Hi,

I've just started using this and like it so far. There's one thing I can't work out how to do, I'm hoping someone can help me with this.

I have windows focus set to where my cursor is, so if emacs-anywhere starts somewhere outside of my cursor position, then it doesn't get focus.

I'm thinking the best solution to this would be to position the middle of the emacs-anywhere window just under the cursor.

Thanks in advance,

tecosaur.

p.s. I don't know if this is relevant, but I'm setting the size with `(set-frame-size (selected-frame) 80 12)`

**Comment by zachcurry** [comment]
Hi @tecosaur,
I'm glad to hear you are getting some use out of this project.

If I am understanding the issue correctly, it happens because of the way your window manager is configured (i.e., to focus the application which is under your mouse cursor). As it stands now, we don't provide any information about the cursor's position, but if we did, I suspect that you could make use of this information to position the newly created Emacs frame in the manner you have suggested.

At first glance, two possible solutions come to mind. The first solution, which is perhaps suboptimal for your situation, would be to set the position and size of the new frame such that it covers the focused window completely. This would fix the focus problem, but would prevent you from seeing the content of the other window as you work in Emacs. The second solution would be to get the mouse position and use it to position the frame. This could be something you do on your end within your hook function, or, if you think you could extend this project to help facilitate this use case without any breaking changes, code it up and submit a pull request.

Thanks for bringing this issue to our attention, @tecosaur. I wish I had a better answer for you. Let me know if you find a satisfactory solution, or if you have anymore questions.

**Comment by tecosaur** [comment]
Hmm. I've had a look and this seems useful. Perhaps we could add some some env vars like `EA_MOUSE_X`?
```
$ xdotool getmouselocation --shell
X=1015
Y=688
SCREEN=0
WINDOW=132120581
```

**Comment by tecosaur** [comment]
> The second solution would be to get the mouse position and use it to position the frame. This could be something you do on your end within your hook function

Well, I've managed to get it working with
```lisp
(let* ((mousepos (split-string (shell-command-to-string "xdotool getmouselocation | sed -E \"s/ screen:0 window:[^ ]*|x:|y://g\"")))
         (mouse-x (- (string-to-number (nth 0 mousepos)) 100))
         (mouse-y (- (string-to-number (nth 1 mousepos)) 50)))
  (set-frame-position (selected-frame) mouse-x mouse-y))
```
So I'll close the issue for now :)

**Comment by zachcurry** [comment]
Nice! I'm glad you've got something working, @tecosaur!

Do you think we should add this example to the README?

**Comment by tecosaur** [comment]
I'm not sure if it's a common 'issue', but I know that I personally prefer the positioning; simply on the basis that my attention is usually around where the cursor currently is.

As to whether it would benefit the readme, I'll leave you to judge :)

**Comment by zachcurry** [comment]
For now, I'll keep this issue in the back of my mind. If we get more questions like this, I'll definitely throw it in the README.

Thanks again for bringing this to everyone's attention and for sharing your solution.
